DROP TABLE COBRANCA;
DROP TABLE REQUISICAO_EMAIL;

CREATE TABLE COBRANCA(ID BIGINT PRIMARY KEY, CICLISTA BIGINT, HORA_FINALIZACAO TIMESTAMP(6), HORA_SOLICITACAO TIMESTAMP(6), STATUS TINYINT, VALOR NUMERIC(38,2));
CREATE TABLE REQUISICAO_EMAIL(ID BIGINT PRIMARY KEY, ASSUNTO CHARACTER VARYING(255), EMAIL CHARACTER VARYING(255), MENSAGEM CHARACTER VARYING(255));
